version: '3'

services:

### PHP-FPM Container #######################################

  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ${WEB_ROOT}:/var/www/html
    expose:
      - "9000"
    depends_on:
      - redis
    restart: always

### Nginx Server Container ##################################

  nginx:
    build:
      context: ./nginx
    volumes:
        - ${WEB_ROOT}:/var/www/html
    ports:
        - "${NGINX_HTTP_PORT}:80"
        - "${NGINX_HTTPS_PORT}:443"
    depends_on:
        - php-fpm
    restart: always

### Redis Container #########################################

  redis:
    image: redis:5
    expose:
      - "6379"
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ../data/redis:/data
    restart: always

### Volumes Setup ###########################################
networks:
  default:
    external:
      name: ${USER_NETWORK}
